services:
  favly-db:
    image: npgsql/postgres:latest
    container_name: favly-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker178
      - POSTGRES_DB=favly_db
    ports:
      - "5432:5432"
    volumes:
      - favly_data:/var/lib/postgresql/data

volumes:
  favly_data:

      